AdminPortal/Models/CardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminPortal.Models
{
    public class AssignCostViewModel
    {
        public int Cost { get; set; }
        public List<int> Ids { get; set; } 
    }
    public class ItemDetails
    {
        public short Id { get; set; }
        public string Value { get; set; }
        public bool IsActive { get; set; }
    }

    public class iCardCompanyDetails
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Logo { get; set; }
        public string Website { get; set; }
        public bool IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
    
    public class CompanyContact
    {
        public int CompanyId { get; set; }
        public Guid? Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

AdminPortal/Controllers/CardController.cs
using AdminPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.IO;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;

namespace AdminPortal.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CardController : Controller
    {
        private ApplicationUserManager _userManager = null;
        private const int ACTIVAITON_CODE_LENGTH = 6;
        public ApplicationUserManager UserManager
        {
            get
            {
                if(_userManager == null)
                {

                    //var dbContext = new IdentityDbContext(System.Configuration.ConfigurationManager.ConnectionStrings["omelette_CardsEntities_Identity"].ConnectionString);
                    //var userStore = new UserStore<ApplicationUser>(dbContext);
                    //_userManager = new ApplicationUserManager(userStore);
                    _userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext(System.Configuration.ConfigurationManager.ConnectionStrings["omelette_CardsEntities_Identity"].ConnectionString)));

                    //_userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext(System.Configuration.ConfigurationManager.ConnectionStrings["omelette_CardsEntities_Identity"].ConnectionString)));
                }

                return _userManager;
            }
        }
        // GET: Card
        public ActionResult Index()
        {
            return View();
        }

        #region Templates
        public ActionResult Template()
        {

            return View();
        }

        public PartialViewResult GetTemplateList()
        {
            var listFromDB = BLLayer.iCardMgr.GetCardTemplates(0);
            return PartialView("_TemplateList", listFromDB);
        }
        public JsonResult RefreshTemplates()
        {
            var ftpFiles = OmeletteSoft.BLLayer.FTPMgr.DirectoryListSimple("/card.omeletteinc.com/Cards");
            var listFromDB = BLLayer.iCardMgr.GetCardTemplates(0);
            var cardTemplates = new List<Entities.iCard.CardTemplate>();

            foreach (var file in ftpFiles)
            {
                var dbItem = listFromDB.FirstOrDefault(e => e.CardTemplatePath.ToUpper().EndsWith(file.ToUpper()));
                if (dbItem == null && !string.IsNullOrEmpty(file))
                {
                    cardTemplates.Add(new Entities.iCard.CardTemplate()
                    {
                        CardTemplateId = 0,
                        CardTemplateName = file,
                        CardTemplatePath = $"http://card.omeletteinc.com/Cards/{file}",
                        Cost = 0
                    });
                }
            }

            foreach (var cardTemplate in cardTemplates)
            {
                BLLayer.iCardMgr.SaveCardTemplate(cardTemplate.CardTemplateId, cardTemplate.CardTemplateName, cardTemplate.CardTemplatePath, true, cardTemplate.Cost, 0);
            }
            listFromDB = BLLayer.iCardMgr.GetCardTemplates(0);
            return Json(new {Message="Refreshed Images from Server." });
        }
        [HttpPost]
        public JsonResult AssignCost(AssignCostViewModel input)
        {
            if(input.Cost >= 0)
            {
                if (input.Ids.Any())
                {
                    BLLayer.iCardMgr.AssignCostToCard(input.Cost, input.Ids.ToArray());
                    return Json(new { Message = "Assigned Cost successfully.", Id=0 });
                }
                else
                {
                    return Json(new { Message = "No files are selected.", Id = -1 });
                }
            }
            else
            {
                return Json(new { Message = "Invalid Cost.", Id = -1 });
            }
            
        }
        #endregion

        
        #region Communication Types
        public ActionResult CommunicationType()
        {
            return View();
        }
        public PartialViewResult GetCommunicationDetails(int id)
        {
            DALayer.GetCommunicationTypes_Result communicationTypeDetails = null;
            if (id > 0)
                communicationTypeDetails = BLLayer.iCardMgr.GetCommunicationTypes().FirstOrDefault(e => e.CommunicationTypeId == id);

            if (communicationTypeDetails == null)
                communicationTypeDetails = new DALayer.GetCommunicationTypes_Result() {
                    CommunicationTypeId = 0,
                    IsActive = true,
                    CommunicationTypeName = string.Empty
                };

            return PartialView("_CommunicationTypeDetails", communicationTypeDetails);
        }

        public PartialViewResult GetCommunicationTypeList()
        {
            var communicationTypes = BLLayer.iCardMgr.GetCommunicationTypes();
            return PartialView("_CommunicationTypeList", communicationTypes);
        }

        [HttpPost]
        public JsonResult SaveCommunicationType(ItemDetails item)
        {
            if(string.IsNullOrEmpty(item.Value))
            {
                return Json(new { Message = "Can't Save empty Communication Type.", Id = -1 });
            }
            BLLayer.iCardMgr.SaveCommunicationType(item.Id, item.Value, item.IsActive);
            return Json(new { Message = "Succesfully saved Communication Type.", Id = 0 });
        }
        #endregion

        #region Social
        
        public ActionResult SocialType()
        {
            return View();
        }
        public PartialViewResult GetSocialTypeDetails(int id)
        {
            DALayer.GetSocialTypes_Result socialTypes = null;
            if (id > 0)
                socialTypes = BLLayer.iCardMgr.GetSocialTypes().FirstOrDefault(e => e.SocialTypeId == id);

            if (socialTypes == null)
                socialTypes = new DALayer.GetSocialTypes_Result()
                {
                    SocialTypeId=0,
                    IsActive = true,
                    SocialTypeName = string.Empty
                };

            return PartialView("_SocialTypeDetails", socialTypes);
        }

        public PartialViewResult GetSocialTypeList()
        {
            var communicationTypes = BLLayer.iCardMgr.GetSocialTypes();
            return PartialView("_SocialTypeList", communicationTypes);
        }

        [HttpPost]
        public JsonResult SaveSocialType(ItemDetails item)
        {
            if (string.IsNullOrEmpty(item.Value))
            {
                return Json(new { Message = "Can't Save empty Social Type.", Id = -1 });
            }
            BLLayer.iCardMgr.SaveSocialType(item.Id, item.Value, item.IsActive);
            return Json(new { Message = "Succesfully saved Social Type.", Id = 0 });
        }
        #endregion

        #region Campanies
        public ActionResult Campanies()
        {
            return View();
        }
        public PartialViewResult GetCompanyDetails(int? id, string name)
        {
            var companies = BLLayer.iCardMgr.GetCompanies(id ?? 0, name ?? string.Empty);

            return PartialView("_CompaniesList", companies);
        }
        public PartialViewResult CompanyDetails(int id)
        {
            var companyDetails = new iCardCompanyDetails();
            if (id > 0)
            {
                companyDetails = BLLayer.iCardMgr.GetCompanies(id, string.Empty)
                    .Select(e=> new iCardCompanyDetails()
                    {
                        Id = e.CompanyId,
                        Name = e.Name,
                        Address= e.Address,
                        Logo = e.LogoImage,
                        Website = e.WebSite,
                        IsActive = e.IsActive.Value,
                        CreatedDate = e.CreateDate,
                        ModifiedDate = e.ModifiedDate
                    })
                    .FirstOrDefault();
            }

            if(companyDetails == null)
            {
                companyDetails = new iCardCompanyDetails()
                {
                    IsActive = true,
                    Id = 0
                };
            }
            return PartialView("_CompanyDetails", companyDetails);
        }
        [HttpPost]
        public JsonResult SaveCompany(iCardCompanyDetails company)
        {
            if (string.IsNullOrEmpty(company.Name))
            {
                return Json(new { Message = "Can't Save empty Company. Name is empty", Id = -1 });
            }
            if (string.IsNullOrEmpty(company.Address))
            {
                return Json(new { Message = "Can't Save empty Company. Address is empty", Id = -1 });
            }
            var userId = User.Identity.GetUserId();


            BLLayer.iCardMgr.SaveCompany(company.Id, company.Name, company.Address, company.Logo, company.Website, new Guid(userId));
            return Json(new { Message = "Succesfully saved Social Type.", Id = 0 });
        }
        public ActionResult ViewCompanyDetails(int id)
        {
            var companyDetails = BLLayer.iCardMgr.GetCompanies(id, string.Empty)
                    .Select(e => new iCardCompanyDetails()
                    {
                        Id = e.CompanyId,
                        Name = e.Name,
                        Address = e.Address,
                        Logo = e.LogoImage,
                        Website = e.WebSite,
                        IsActive = e.IsActive.Value,
                        CreatedDate = e.CreateDate,
                        ModifiedDate = e.ModifiedDate
                    })
                    .FirstOrDefault();
            return View(companyDetails);
        }

        public PartialViewResult CompanyCardList(int id)
        {

AdminPortal/Views/Card/Campanies.cshtml
@{
    ViewBag.Title = "Campanies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h3 class="page-title">Companies</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Card">Card</a></li>
            <li class="breadcrumb-item active" aria-current="page">Companies</li>
        </ol>
    </nav>
</div>
@if (!string.IsNullOrEmpty(ViewBag.Success))
{
    <div class="alert alert-success">
        <strong>@ViewBag.Success</strong>
    </div>
}
@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div class="alert alert-danger">
        <strong>@ViewBag.Error</strong>
    </div>
}
<div class="row float-right">
    <button type="button" id="btnNew" class="btn btn-primary" class="btn btn-default">Add New Company</button>
</div>
<div id="divList">

</div>

@section scripts{
    <script language="javascript">
        $(document).ready(function () {
            loadList();
            $('#btnNew').click(function () {
                addEditCompany(0);
            });
        });
    var addEditCompany= function(id) {

        var url = encodeURI("@Url.Action("CompanyDetails", "Card")" + "?id=" + id);
        if (id > 0)
            showDetails("Edit Company Type", url);
        else
            showDetails("Add Company Type", url);
    }
    
        var loadList = function () {
            var url = encodeURI("@Url.Action("GetCompanyDetails", "Card")?id=0");
            $('#divList').load(url);
        }
    </script>
}

AdminPortal/Views/Card/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
            <i class="mdi mdi-home"></i>
        </span> Home
    </h3>
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
            </li>
        </ul>
    </nav>
</div>

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div id="divList">
                    <div class="spinner-grow d-none" role="status" id="divSpinner">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalHeading">Impact Factor</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">

                <div id="divModalBody"></div>
            </div>
            @*<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>*@
        </div>
    </div>
</div>

@section scripts{
    <script language="javascript">
        $(document).ready(function () {


        });


        var showDetails = function (message, url) {
            $('#myModal').modal('show');

            $('#modalHeading').text(message);
            $("#divModalBody").load(url);
        }

        var updateAlertMessage = function (msg) {
            $('#divAlert').show();
            $('#alertMessage').text(msg);
        }
    </script>
}

AdminPortal/Views/Card/SocialType.cshtml
@{
    ViewBag.Title = "SocialType";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h3 class="page-title">Social Types</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Card">Card</a></li>
            <li class="breadcrumb-item active" aria-current="page">Social Types</li>
        </ol>
    </nav>
</div>
@if (!string.IsNullOrEmpty(ViewBag.Success))
{
    <div class="alert alert-success">
        <strong>@ViewBag.Success</strong>
    </div>
}
@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div class="alert alert-danger">
        <strong>@ViewBag.Error</strong>
    </div>
}
<div class="row float-right">
    <button type="button" id="btnNew" class="btn btn-primary" class="btn btn-default">Add New</button>
</div>
<div id="divList">

</div>
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalHeading">Heading</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">

                <div id="divModalBody"></div>
            </div>
            @*<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>*@
        </div>
    </div>
</div>
@section scripts{
    <script language="javascript">
        $(document).ready(function () {
            loadList();
            $('#btnNew').click(function () {
                addEditType(0);
            });
        });
    var addEditType= function(id) {

        var url = encodeURI("@Url.Action("GetSocialTypeDetails", "Card")" + "?id=" + id);
        if (id > 0)
            showDetails("Edit Social Type", url);
        else
            showDetails("Add Social Type", url);
    }
    var showDetails = function (message, url) {
            $('#myModal').modal('show');

            $('#modalHeading').text(message);
            $("#divModalBody").load(url);
        }
        var loadList = function () {
            var url = encodeURI("@Url.Action("GetSocialTypeList", "Card")");
            $('#divList').load(url);
        }
        var hideDetails = function () {
            $('#myModal').modal('hide');

            $('#modalHeading').text('');
            $("#divList").html('');
        }
        var updateAlertMessage = function (msg) {
            $('#divAlert').show();
            $('#alertMessage').text(msg);
        }
    </script>
}

AdminPortal/Views/Card/ViewCompanyDetails.cshtml
@model AdminPortal.Models.iCardCompanyDetails
@{
    ViewBag.Title = "ViewCompanyDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h3 class="page-title">Company Details</h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/Card">Card</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="/Card/Companies">Companies</a></li>
            <li class="breadcrumb-item active" aria-current="page">View Details</li>
        </ol>
    </nav>
</div>
@if (!string.IsNullOrEmpty(ViewBag.Success))
{
    <div class="alert alert-success">
        <strong>@ViewBag.Success</strong>
    </div>
}
@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div class="alert alert-danger">
        <strong>@ViewBag.Error</strong>
    </div>
}
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-chart-area"></i>
        <b>Company Details</b>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">Name</dt>
            <dd class="col-sm-9">@Model.Name</dd>

            <dt class="col-sm-3">Address</dt>
            <dd class="col-sm-9">@Model.Address</dd>

            <dt class="col-sm-3">Website</dt>
            <dd class="col-sm-9">@Model.Website</dd>

            <dt class="col-sm-3 text-truncate">Is Active</dt>
            <dd class="col-sm-9">@(Model.IsActive == true ? "Yes" : "No")</dd>
        </dl>
    </div>
    <div class="card-footer small text-muted">Updated on: @Model.ModifiedDate.Value.ToLongDateString() @Model.ModifiedDate.Value.ToLongTimeString()</div>
</div>
<div class="card mb-3">
    <div class="card-header">
        <b>Cards</b>
        <div class="row float-right">
            <button type="button" id="btnNewCard" class="btn btn-success">Add Card</button>
        </div>
    </div>
    <div class="card-body">
        <div id="divCompanyCards"></div>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header">
        <b>Users</b>
        <div class="row float-right">
            <input type="text" id="userSearch" />
            <button type="button" id="btnSearch" class="btn btn-success">Search</button>
            &nbsp;&nbsp;
            <button type="button" id="btnNewUser" class="btn btn-success">Add User</button>
            &nbsp;&nbsp;
            <button type="button" id="btnBulkAddUsers" class="btn btn-success">Bulk Add Users</button>
        </div>
    </div>
    <div class="card-body">
        <div id="divCompanyUsers"></div>
    </div>
</div>
@section scripts{
    <script language="javascript">
        $(document).ready(function () {
            loadCompanyCards();
            loadCompanyUsers();

            $('#btnNewCard').click(function () {
                loadCardUpload();
            });
            $('#btnNewUser').click(function () {
                loadUserAddEdit();
            });
            $('#btnSearch').click(function () {
                loadCompanyUsers();
            });
            $('#btnBulkAddUsers').click(function () {
                loadBulkAddUsers();
            });
        });
        var loadCompanyCards = function () {
            var url = encodeURI("@Url.Action("CompanyCardList", "Card")?id=@Model.Id");
            $('#divCompanyCards').load(url);
        }
        var loadCompanyUsers = function () {
            var url = encodeURI("@Url.Action("CompanyUserList", "Card")?id=@Model.Id&search="+$('#userSearch').val());
            $('#divCompanyUsers').load(url);
        }
        var loadCardUpload = function () {
            var url = encodeURI("@Url.Action("CompanyCardUpload", "Card")" + "?id=@Model.Id");
            showDetails("Add Cards to Company", url);
        }
        var loadUserAddEdit = function (contactId) {
            var url = encodeURI("@Url.Action("CompanyUserAddEdit", "Card")" + "?cid=@Model.Id&id=" + contactId);
            showDetails("Add / Edit Company User", url);
        }
        var loadBulkAddUsers = function (contactId) {
            var url = encodeURI("@Url.Action("CompanyUserUpload", "Card")" + "?cid=@Model.Id");
            showDetails("Bulk Add Users ", url);
        }
    </script>
}

AdminPortal/Views/Card/_CommunicationTypeList.cshtml
@model IEnumerable<DALayer.GetCommunicationTypes_Result>
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Id</th>
            <th>Name</th>
            <th>Is Active?</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @{
            var index = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@(index++).</td>
                <td>@item.CommunicationTypeId</td>
                <td>@item.CommunicationTypeName</td>
                <td>@(item.IsActive.Value == true ? Html.Raw("<i class='mdi mdi-thumb-up'></i>") : Html.Raw("<i class='mdi mdi-thumb-down-outline'></i>"))</td>
                <td><a href="#" onclick="addEditType(@item.CommunicationTypeId)">Edit</a></td>
            </tr>
        }
    </tbody>
</table>

AdminPortal/Views/Card/_CompanyCardUpload.cshtml
@model Int32
<link rel="stylesheet" href="@Url.Content("~/Content/jquery.fileupload.css")">
<script src="@Url.Content("~/scripts/jquery.ui.widget.js")"></script>
<script src="@Url.Content("~/scripts/jquery.iframe-transport.js")"></script>
<script src="@Url.Content("~/scripts/jquery.fileupload.js")"></script>

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <span>
                    <b>Select image(s) for Company Cards</b>
                </span>
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Select files...</span>
                    <!-- The file input field used as target for the file upload widget -->
                    <input id="fileupload" type="file" name="files[]" multiple accept="image/*"/>
                </span>
                <br /><br />
                <!-- The global progress bar -->
                <div id="progress" class="progress">
                    <div class="progress-bar progress-bar-success"></div>
                </div>
                <!-- The container for the uploaded files -->
                <div id="files" class="files"></div>
                <br />
                <div id="divResult" class="alert alert-success">

                </div>
            </div>
        </div>
    </div>
</div>
<script>
        /*jslint unparam: true */
        /*global window, $ */
        $(function () {
            'use strict';
            // Change this to the location of your server-side upload handler:
            var url = '@Url.Action("CompanyCardUploadFile","Card")?id=@Model';
            $('#fileupload').fileupload({
                url: url,
                dataType: 'json',
                done: function (e, data) {

                    if (data.result && data.result.result && data.result.result.error) {
                        $('#divResult').html("Error occured: <p class='text-danger'>" + data.result.result.error + "</p>");
                    }

                    if (data.result && data.result.result && data.result.result.totalProcessedCount) {
                        $('#divResult').append("<br/>Total records processed : <strong>" + data.result.result.totalProcessedCount + "</strong>");
                    }
                    //Refresh parent grid
                    loadCompanyCards();

                    hideDetails();
                    updateAlertMessage("Card(s) added to Company.");
                },
                progressall: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    $('#progress .progress-bar').css(
                        'width',
                        progress + '%'
                    );
                    $('#divResult').html('<strong>Procesing file content...</strong><img src="@Url.Content("~/images/loading.gif")" height="32px" width="32px" />');
                    
                },
                processdone: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    $('#progress .progress-bar').css(
                        'width',
                        progress + '%'
                    );
                    $('#divResult').html('<strong>Procesing file content...</strong><img src="@Url.Content("~/images/loading.gif")" height="32px" width="32px" />');


                }
            }).prop('disabled', !$.support.fileInput)
                .parent().addClass($.support.fileInput ? undefined : 'disabled');
        });
</script>

AdminPortal/Views/Card/_CompanyDetails.cshtml
@model AdminPortal.Models.iCardCompanyDetails
    <form>
        <div class="form-group">
            <label for="companyName">Company Name:</label>
            <input type="text" maxlength="250" class="form-control" id="companyName" value="@Model.Name">
        </div>
        <div class="form-group">
            <label for="companyAddress">Address:</label>
            <input type="text" maxlength="100" class="form-control" id="companyAddress" value="@Model.Address">
        </div>
        <div class="form-group">
            <label for="companyWebsite">Website:</label>
            <input type="text" maxlength="250" class="form-control" id="companyWebsite" value="@Model.Website">
        </div>
        <div class="checkbox">
            <label><input type="checkbox" name="isActiveRadio" id="isActiveRadio" value="1" @(Model.IsActive ? "checked" : "")> Is Active?</label>
        </div>
        <button type="button" id="btnSaveCompany" class="btn btn-primary btn-default" >Submit</button>
        <input type="hidden" id="id" value="@Model.Id"/>
    </form>
<script language="javascript">
    $(document).ready(function () {
        $('#btnSaveCompany').click(function () {
            var data = {
                id: $('#id').val(),
                name: $('#companyName').val(),
                address: $('#companyAddress').val(),
                website: $('#companyWebsite').val(),
                isActive: $('#isActiveRadio').prop("checked")
                };
            $.ajax({
                    type: "POST",
                    url: "@Url.Action("SaveCompany", "Card")",
                    data: data,
                    success: function (result) {
                        hideDetails();

                        updateAlertMessage(result.Message);
                        if (result.Id >= 0) {
                            loadList();
                        }
                    }
                });
        });
    });
</script>

AdminPortal/Views/Card/_CompanyUserAddEdit.cshtml
@model DALayer.GetCompanyContacts_Result
<form>
    <div class="form-group">
        <label for="username">Email:</label>
        <input type="text" maxlength="250" class="form-control" id="email" value="@Model.Email">
    </div>
    <div class="form-group">
        <label for="companyAddress">First Name:</label>
        <input type="text" maxlength="200" class="form-control" id="firstName" value="@Model.FirstName">
    </div>
    <div class="form-group">
        <label for="companyAddress">Last Name:</label>
        <input type="text" maxlength="200" class="form-control" id="lastName" value="@Model.LastName">
    </div>
    <button type="button" id="btnSaveContact" class="btn btn-primary btn-default">Submit</button>
    <input type="hidden" id="id" value="@Model.UniqueId" />
    <input type="hidden" id="companyId" value="@Model.CompanyId" />
</form>
<script language="javascript">
    $(document).ready(function () {
        $('#btnSaveContact').click(function () {
            var data = {
                id: $('#id').val(),
                companyId: $('#companyId').val(),
                email: $('#email').val(),
                firstName: $('#firstName').val(),
                lastName: $('#lastName').val()
            };

            $.ajax({
                    type: "POST",
                    url: "@Url.Action("SaveCompanyContact", "Card")",
                    data: data,
                    success: function (result) {
                        hideDetails();
                        console.log(result);
                        updateAlertMessage(result.Message);
                        if (result.Id >= 0) {
                            loadList();
                        }
                    }
            });
        });
    });
</script>

AdminPortal/Views/Card/_SocialTypeDetails.cshtml
@model DALayer.GetSocialTypes_Result
<form>
    <div class="form-group">
        <label for="email">Social Type Id:</label>
        <input type="text" readonly class="form-control" id="id" value="@Model.SocialTypeId">
    </div>
    <div class="form-group">
        <label for="pwd">Social Type Name:</label>
        <input type="text" maxlength="30" class="form-control" id="socialTypeName" value="@Model.SocialTypeName">
    </div>
    <div class="checkbox">
        <label><input type="checkbox" name="isActiveRadio" id="isActiveRadio" value="1" @(Model.IsActive.Value ? "checked" : "")> Is Active?</label>
    </div>
    <button type="button" id="btnSaveSocial" class="btn btn-primary" class="btn btn-default">Submit</button>
</form>
<script language="javascript">
    $(document).ready(function () {
        $('#btnSaveSocial').click(function () {
            var data = {
                id: $('#id').val(),
                value: $('#socialTypeName').val(),
                isActive: $('#isActiveRadio').prop("checked")
                };
            $.ajax({
                    type: "POST",
                    url: "@Url.Action("SaveSocialType", "Card")",
                    data: data,
                    success: function (result) {
                        hideDetails();

                        updateAlertMessage(result.Message);
                        if (result.Id >= 0) {
                            loadList();
                        }
                    }
                });
        });
    });
</script>